[terminal] 
shell = { program = "/bin/zsh", args = ["-l","-c","tmux"] }

[window]
decorations = "None"

[window.padding]
x = 1
y = 1

[font]
size = 9.0

[font.offset]
y = -2

[font.normal]
family = "Monaco"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[scrolling]
history = 10000
multiplier = 3

# Base16 Gruvbox Material Dark, Hard 256 - alacritty color config
# Mayush Kumar (https = //github.com/MayushKumar), sainnhe (https = //github.com/sainnhe/gruvbox-material-vscode)
[colors]
indexed_colors = [{index = 16, color = "0xe78a4e"},{index = 17, color = "0xbd6f3e"},{index = 18, color = "0x2a2827"},{index = 19, color = "0x504945"},{index = 20, color = "0xbdae93"},{index = 21, color = "0xebdbb2"}]

# Default colors
[colors.primary]
background = "0x000000"
foreground = "0xffffff"

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "0x202020"
cursor = "0x8fee96"

# Normal colors
[colors.normal]
black = "0x202020"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xddc7a1"

# Bright colors
[colors.bright]
black = "0x5a524c"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xd8a657"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xfbf1c7"


